In [1]:
import numpy as np

In [102]:
from sklearn.datasets import load_breast_cancer
data_set = load_breast_cancer()
X = data_set.data
y = data_set.target
alpha=0.1
number_of_itterations=2000
np.random.seed(42)
theta = np.random.randn(30)

In [106]:
len(data.target)

569

In [107]:
X.shape

(569, 30)

In [108]:
def sigmoid(X):
    return 1 / (1 + np.exp(-X))

In [109]:
sigmoid(X).shape

(569, 30)

In [112]:
np.matmul(X,theta)

array([ -1.51231973e+03,  -7.73270390e+02,  -6.52588418e+02,
        -1.98216609e+02,  -3.13988838e+02,  -3.00997382e+02,
        -6.86274219e+02,  -4.07382690e+02,  -2.25889852e+02,
        -2.59533704e+02,  -4.01343785e+02,  -6.59903637e+02,
        -2.83612907e+02,  -2.94300570e+01,  -6.45511414e+01,
        -3.12007211e+02,  -5.71068306e+02,  -6.53062148e+02,
        -1.57594304e+03,  -1.10450136e+02,  -5.21062215e+01,
        -4.11202281e+00,  -3.08540070e+02,  -1.62384489e+03,
        -1.85432906e+03,  -7.84841624e+02,  -2.42947131e+02,
        -3.91996177e+02,  -6.74474638e+02,  -2.95214711e+02,
        -7.99869033e+02,  -5.94383806e+02,  -5.64722628e+02,
        -8.16124077e+02,  -5.27674402e+02,  -4.05539673e+02,
        -1.34543688e+02,   6.92127875e+01,  -4.54116543e+01,
        -1.54124198e+02,  -2.22034296e+02,  -1.34794339e+02,
        -7.42683645e+02,  -4.35583670e+02,  -1.91201990e+02,
        -6.05414601e+02,  -6.69605840e+00,  -2.31738690e+02,
        -1.08315941e+02,

In [110]:
def hypothesis(X, theta):
    return sigmoid(np.matmul(X,theta))

In [111]:
hypothesis(X, theta).shape

/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


(569,)

In [69]:
def loss_function(target, predicted):
    return (1-target)*np.log(1-predicted)+target*np.log(predicted)

In [71]:
loss_function(y, hypothesis(X,theta)).shape

(569,)

In [72]:
def cost_function(X,y,theta):
    return -loss_function(y,hypothesis(X,theta)).sum()/len(y)

In [100]:
cost_function(X,y,theta)

80.537835609311088

In [84]:
def derivative(X,y,theta):
    return np.matmul(hypothesis(X,theta) - y,X)/len(y)

In [86]:
derivative(X,y,theta).shape

(30,)

In [98]:
def gradient_step(X,y,theta,alpha):
    return theta - alpha*derivative(X,y,theta)

In [99]:
gradient_step(X,y,theta,alpha)

array([ -1.28132514e+00,   9.42672580e-01,   2.91912532e+00,
         2.90321536e+01,   2.78889905e-02,  -3.36784669e+00,
         3.79294970e-01,   4.49075894e-01,   2.36964058e-01,
        -9.32012647e-01,   1.19147052e+00,  -1.92000456e+00,
        -2.98624665e+00,   1.92292425e+00,   5.08735255e-01,
         1.38158520e+00,  -7.74864638e-01,  -6.07560933e-01,
        -5.15682940e-01,  -6.90964604e-01,  -1.23291737e+00,
         9.71023367e-01,   7.32986131e+00,   3.49381239e+01,
         2.15363686e+00,  -5.96368427e-01,  -9.37134062e-02,
         5.49009464e-01,   1.16550983e+00,   5.94533940e-01])

In [95]:
def gradient_descent(X,y,theta,alpha,num_iters):
    for i in range(num_iters):
        theta = gradient_step(X,y,theta,alpha)
        if i % 50 == 0:
            print(i)
            print(cost_function(X,y,theta))
        

In [101]:
cost_function(X,y,gradient_step(X,y,theta,alpha))

/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  


nan

In [96]:
gradient_descent(X,y,theta,alpha,number_of_itterations)

0
nan
50
nan
100
nan
150
nan
200
nan
250
nan
300
nan
350
nan
400
nan
450
nan
500
nan
550
nan
600
nan
650
nan
700
nan
750
nan
800
nan
850
nan
900
nan
950
nan
1000
nan
1050
nan
1100
nan
1150
nan
1200
nan
1250
nan
1300
nan
1350
nan
1400
nan
1450
nan
1500
nan
1550
nan
1600
nan
1650
nan
1700
nan
1750
nan
1800
nan
1850
nan
1900
nan
1950
nan


/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  
/home/wolfenfeld/anaconda3/envs/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [44]:
X*theta

array([[ -3.67610919e+01,  -1.88219686e+00,  -2.43077030e+02, ...,
          1.44467492e-01,   5.28449766e-01,   7.00974490e-02],
       [ -4.20331106e+01,  -3.22221948e+00,  -2.63069522e+02, ...,
          1.01246999e-01,   3.15852392e-01,   5.24817066e-02],
       [ -4.02349027e+01,  -3.85324502e+00,  -2.57329104e+02, ...,
          1.32274305e-01,   4.14972615e-01,   5.16327551e-02],
       ..., 
       [ -3.39207407e+01,  -5.09172330e+00,  -2.14374938e+02, ...,
          7.71872281e-02,   2.54749311e-01,   4.61027798e-02],
       [ -4.20944132e+01,  -5.31838477e+00,  -2.77321595e+02, ...,
          1.44249756e-01,   4.69414082e-01,   7.31041520e-02],
       [ -1.58569246e+01,  -4.44981801e+00,  -9.48554665e+01, ...,
          0.00000000e+00,   3.29749897e-01,   4.14983973e-02]])

In [40]:
(theta*X).shape

(569, 30)

In [42]:
hypothesis(theta,X).shape

(569, 30)

In [36]:
sigmoid(theta)

array([ 0.11471914,  0.45479151,  0.12137699,  0.49898303,  0.50552147,
        0.03315415,  0.5930058 ,  0.61003571,  0.55626946,  0.28171772,
        0.76380355,  0.11956318,  0.04262517,  0.64493991,  0.62440406,
        0.79902956,  0.31507563,  0.35247461,  0.37355999,  0.3337678 ,
        0.11180965,  0.37651872,  0.8665699 ,  0.4680062 ,  0.89527534,
        0.35255445,  0.47398765,  0.63282113,  0.75924673,  0.6432618 ])

In [ ]:
def cost_function(X,y,theta):
    number_of_samples, number_of_features = X.shape
    for i in xrange(number_of_samples)
    